// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXdhFZwo_3fIv5q228qMjhKzBaQAUsp7U',
    appId: '1:935560339177:web:3af83c584344e44a4fda78',
    messagingSenderId: '935560339177',
    projectId: 'med-g-8fd5f',
    authDomain: 'med-g-8fd5f.firebaseapp.com',
    storageBucket: 'med-g-8fd5f.appspot.com',
    measurementId: 'G-EG3ZZX9290',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo_iKZHybg-_IIkH3yE3S3AJ7dx8wv7qc',
    appId: '1:935560339177:android:6657ae794c8a397e4fda78',
    messagingSenderId: '935560339177',
    projectId: 'med-g-8fd5f',
    storageBucket: 'med-g-8fd5f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwh-5pgUDdr3G1DuD-h-BP0QO5ki4PjpM',
    appId: '1:935560339177:ios:1ff705f43f29c79c4fda78',
    messagingSenderId: '935560339177',
    projectId: 'med-g-8fd5f',
    storageBucket: 'med-g-8fd5f.appspot.com',
    iosBundleId: 'com.example.medg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwh-5pgUDdr3G1DuD-h-BP0QO5ki4PjpM',
    appId: '1:935560339177:ios:ab9b8392016258414fda78',
    messagingSenderId: '935560339177',
    projectId: 'med-g-8fd5f',
    storageBucket: 'med-g-8fd5f.appspot.com',
    iosBundleId: 'com.example.medg.RunnerTests',
  );
}
